import { LegalPage, type LegalSection } from "@/components/legal/LegalPage";

const sections: LegalSection[] = [
  { id: "overview", title: "Cookies and browser storage", paragraphs: ["Cookies are small pieces of data stored by a website or service in your browser. Similar technologies include local storage and session storage. They can support security, preferences, analytics or advertising. This policy describes the current website configuration rather than promising that no infrastructure provider can ever set a cookie."] },
  { id: "site", title: "What this website uses", paragraphs: ["The website application does not set its own cookies or use local storage or session storage. It does not include advertising pixels, embedded social-media feeds or an analytics integration. Fonts and site photographs are served with the website.", "Enquiry-form fields, the prepared email draft and the choice to load a map are held in the current page’s memory. They are not saved as a website cookie or browser-storage preference, and are cleared when that page is reloaded. No email is sent by preparing the form."] },
  { id: "hosting", title: "Hosting and security", paragraphs: ["The website is delivered through Cloudflare. Its services process technical request information to deliver content and protect infrastructure. Depending on the security features applied to a request, Cloudflare may set security cookies, such as cf_clearance for a challenge or __cf_bm for bot protection. Listing these examples does not mean every visitor receives them.", "The website does not use these security mechanisms to run advertising or behavioural analytics. Blocking security cookies may affect access if a security challenge is required. Cloudflare’s own documentation explains which cookies correspond to its enabled features."] },
  { id: "maps", title: "Google Maps is optional", paragraphs: ["Google Maps is not embedded until you choose ‘Load Google Map’ on an office-location panel. Loading it connects your browser to Google, which receives technical information such as your IP address and browser details and may use cookies or account information under its own policies.", "You can leave the map unloaded and use the written office address. ‘Open location in Google Maps’ is an external link that also connects to Google when selected. If you load a map, ‘Hide map’ removes the embed and restores the unloaded panel; it cannot retract information already sent or clear cookies set by Google. Reloading the page leaves the map unloaded again."] },
  { id: "controls", title: "Your choices", paragraphs: ["You can inspect, restrict or delete cookies using your browser settings. Third-party account and privacy settings can also affect what happens when you choose to use Google Maps. You do not need to load Maps to read this site or contact us.", "There is no site-wide ‘accept all’ banner because the current application does not enable analytics or advertising cookies and optional Maps is controlled at the point of use. Any future addition of non-essential tracking requires a fresh assessment, an updated policy and appropriate choices before it is enabled."] },
  { id: "updates", title: "Further information and updates", paragraphs: ["Our Privacy Policy explains enquiry and recruitment information, technical data, your choices and the privacy contact point. This Cookie Policy will be revised when the website’s integrations or storage behaviour changes. Contact us if you would like clarification about a cookie encountered on this website."] },
];

export default function CookiePolicyPage() {
  return <LegalPage title="Cookie Policy" intro="A clear account of website storage, hosting security and the optional Google Maps connection." sections={sections}>
    <div className="mt-8 flex flex-wrap gap-6 text-sm text-[#1f5f9e]">
      <a href="https://developers.cloudflare.com/fundamentals/reference/policies-compliances/cloudflare-cookies/" target="_blank" rel="noopener noreferrer" className="underline">Cloudflare cookie documentation</a>
      <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="underline">Google Privacy Policy</a>
      <a href="https://policies.google.com/technologies/cookies" target="_blank" rel="noopener noreferrer" className="underline">Google cookie information</a>
    </div>
  </LegalPage>;
}
