import { LegalPage, type LegalSection } from "@/components/legal/LegalPage";

const sections: LegalSection[] = [
  { id: "website", title: "About this website", paragraphs: ["This informational website presents YT Associates (AF1112) and Peter Tang & Associates (AF1873). These terms concern use of the website. They do not form a professional-services engagement, quotation or agreement to carry out work. The relevant firm, scope, fees and engagement terms must be agreed separately in writing."] },
  { id: "information", title: "General information, not tailored advice", paragraphs: ["Service descriptions, FAQs and other materials provide general information. They are not audit opinions, legal advice, investment recommendations or tax advice tailored to your circumstances. Laws, regulatory criteria and filing obligations can change and can apply differently to different entities. Obtain current advice for your own situation before acting.", "A service description does not guarantee eligibility for an exemption, incentive, licence, bank account, visa, listing or other approval. Decisions rest with the relevant authority or institution. Regulated activities require the appropriate authorisation; the responsible provider and permitted scope must be confirmed before an engagement."] },
  { id: "engagement", title: "Enquiries and professional engagements", paragraphs: ["Sending an enquiry or CV does not establish a client relationship or oblige either firm to accept an engagement. Acceptance is subject to capacity, suitability, conflicts, independence, applicable regulatory requirements and written agreement. Do not rely on an enquiry being read immediately for a filing deadline or urgent matter.", "An initial website enquiry is not a secure document-submission channel. Please arrange a suitable channel before sharing confidential records, identity documents, payroll data or other sensitive material. Information about how enquiries are handled appears in the Privacy Policy."] },
  { id: "use", title: "Permitted use", paragraphs: ["You may browse and use the site for legitimate information and contact purposes. Do not submit unlawful or misleading material, impersonate another person, introduce malicious software, interfere with availability, attempt unauthorised access or collect personal information from the site for unsolicited marketing."] },
  { id: "rights", title: "Content, images and third-party marks", paragraphs: ["Website materials are protected by applicable intellectual-property rights belonging to their respective owners. You may link to the website and use reasonable excerpts as permitted by law, with appropriate acknowledgement. Reproduction or commercial reuse beyond legal exceptions requires permission from the relevant rights holder.", "Professional-body and authority names, logos and links identify their respective organisations. They do not imply endorsement of this website or authorisation for every service described. Individual professional memberships and firm registrations are distinct matters.", "The people, offices, documents and business scenes used in the site’s illustrative photography include AI-generated or AI-refined images. They do not depict actual staff, clients, premises, records or outcomes unless expressly identified as such."] },
  { id: "external", title: "External websites and optional services", paragraphs: ["External links, including professional-body directories and Google Maps, take you to services operated by third parties. Their terms and privacy practices apply. We do not control their content or operation. Loading an embedded map is optional and is explained in the Cookie Policy."] },
  { id: "limits", title: "Availability and responsibility", paragraphs: ["We aim to keep the website useful and accurate, but cannot guarantee that all information is complete or current, or that the website is always available or error-free. Please report an apparent error to the contact point below.", "To the extent permitted by applicable law, we are not responsible for loss arising solely from relying on general website material instead of obtaining advice appropriate to your circumstances. Nothing in these terms excludes liability that cannot lawfully be excluded, limits statutory rights, or overrides duties owed under an agreed professional engagement."] },
  { id: "law", title: "Applicable law and updates", paragraphs: ["These website terms are governed by Malaysian law, subject to any mandatory laws or rights that apply to you. Contact us first if you have a concern. These terms do not require you to waive a legal remedy or submit to compulsory arbitration.", "Updates will be published with a revised date. Changes to these website terms do not retrospectively alter an existing professional-services agreement."] },
];

export default function TermsPage() {
  return <LegalPage title="Terms & Conditions" intro="The conditions for using this informational website, and how they differ from a professional engagement." sections={sections} />;
}
